### ISSUE TITLE
Stash bonus isn't removed when an upgrade card is played

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#504] opened 2017-12-07 20:24 UTC
The usages stack, but the removal doesn't happen. And then we have weird things, like, widgets at the state of `-1/01`

**Comment by Kazuo256** [comment] 2017-12-10 18:59
Closed via #507

**Comment by OrenjiAkira** [comment] 2017-12-11 02:18
This issue should not have been closed. It happens BECAUSE of the ON_ACT trigger

**Comment by Kazuo256** [comment] 2017-12-11 02:27
Oh, I see. I closed it because there was another bug, very similar, that the ON_ACT solved. In fact, if I understand this right, the problem isn't ON_ACT, but the fact that widgets' state is not checked when no time passes (because upgrade cards spend no time). This probably also happened when the stash trigger was ON_PLAY, it just hasn't gone completely away.

Reopening but rephrasing it.

**Comment by Kazuo256** [comment] 2017-12-12 00:36
Closed via #521

**Closed by Kazuo256** 2017-12-12 00:36 UTC
Labels: bug
